name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: jerray/publish-docker-action@v1.0.3
    - name: Build the Docker image
      uses: benfl3713/departureboard/departure-board@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        repository: benfl3713/departureboard/departure-board
